services:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker-config/mariaDB/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb_data:
